GET http://localhost:3000/project

####
GET http://localhost:3000/project/1

#####
POST http://localhost:3000/project

Content-Type: application/json
{
    "name": "Project 1",
    "description": "Description 1"
}